#!/bin/bash

# create empty directory, move files to process in 
# this script divides by an arbitrary number of chunks 
# variables are : 	1. divide by
#					2. fade length (in seconds; default is 0.002)

#  				./seg 32			## for example would split into 32 equal-sized files.
# ffmpeg seems to have a minimum file length of ~0.017s


filelen=$(for i in *.wav *.aif *.flac *.aiff
	do ffprobe -i "$i" -show_entries format=duration -v quiet -of csv="p=0";done);
divideby=$1	;
length=$(printf "%01.4f" $(echo "scale=6; $filelen / $divideby" | bc ));
fadelen="${2:-0.002}";
fadeoutst=$(printf "%01.4f" $(echo "$length - $fadelen" | bc));

if [ ! -d segmented ];
	then mkdir -p segmented;
	else echo folder exists;
fi && for i in *.wav *.aif *.flac *.aiff

do ffmpeg -i "$i" -f segment -segment_time $length "segmented/${i%*}%02d.wav"; 
done;

cd segmented;
if [ ! -d ../segzc ];
	then mkdir -p ../segzc;
	else echo folder exists;
fi && for i in *.wav;
do ffmpeg -i "$i" -af "afade=t=in:st=0:d=$fadelen,afade=t=out:st=$fadeoutst:d=$fadelen" "../segzc/${i%.*}_zc.wav"; done;
cd ..;
rm -r segmented
