#!/bin/bash

# requires Sox 		https://sourceforge.net/projects/sox/
# 		on macOS, install via: 	Homebrew (brew install sox) 
#								Macports (port install sox)
#
# This script divides any audio file by an arbitrary number of chunks,
# with adjustable fade duration and curve.
#
# INSTRUCTIONS
#
# Create empty directory, move files to process along with this script
# Variables are : 	divideby : number of chunks to split into
#					fadelen : zero-crossing fade 
#							(In seconds, up to 3 decimal spots. The default is 0.001 s.)
#					fadecurve : h (half sine), q (quarter sine; default), 
#								l (logarithmic), p (inverted parabola), t (linear)
# Examples:
#  				./seg 32			: 32 files, 1 ms fade in/out, q curve
#  				./seg 16 0.01		: 16 files, 10 ms fade in/out, q curve
#  				./seg 16 0.002 t	: 16 files, 2 ms fade in/out, t curve


filelen=$(for i in *.wav *.aif *.flac *.aiff
	do soxi -D "$i";done);
divideby=$1	;
length=$(printf "%01.4f" $(echo "scale=6; $filelen / $divideby" | bc ));
fadelen="${2:-0.001}";
fadecurve="${3:-q}";

if [ ! -d segmented ];
	then mkdir -p segmented;
	else echo folder exists;
fi && for i in *.wav *.aif *.flac *.aiff

do
sox "$i" "segmented/${i%*}" trim 0 $length : newfile : restart ;
done;

cd segmented;

stoppos=$(printf $(echo "$(for i in *.wav *.aif *.flac *.aiff
	do soxi -D "$i";done) - $fadelen" | bc));

if [ ! -d ../segzc ];
	then mkdir -p ../segzc;
	else echo folder exists;

fi && for i in *.wav *.aif *.flac *.aiff;
do
sox "$i" "../segzc/${i%.*}_zc.${i#*.}" fade $fadecurve $fadelen $stoppos $fadelen; done;
cd ..;
rm -r segmented
