#!/bin/bash

# Simple script for splitting audio files into chunks of equal length with zero crossings. Requires ffmpeg
# Add this script to your path and run from terminal.
# example : 'segzc 1 0.001' segments any audio in current directory into 1 second chunks with 0.001 fade-in/fade-out into a new folder

length=$1	;
fadelen=$2	;
fadeoutst=$(printf "%01.4f" $(echo "$length - $fadelen" | bc));


if [ ! -d segmented ];
	then mkdir -p segmented;
	else echo folder exists;
fi && for i in *.wav *.aif *.flac *.aiff

do ffmpeg -i "$i" -f segment -segment_time $length "segmented/${i%*}%02d.wav"; 
done;

cd segmented;
mkdir -p segzc;
for i in *.wav;
do ffmpeg -i "$i" -af "afade=t=in:st=0:d=$fadelen,afade=t=out:st=$fadeoutst:d=$fadelen" "segzc/${i%.*}_zc.wav"; done;

mv segzc ../ ;
cd ..;
rm -r segmented
